- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Retrieve Test Vault Credential
      debug: 
        msg: "{{ lookup('env', 'Teste') }}"
