---
- hosts: localhost
  become: no
  tasks:
  - name: Getting local collection list
    shell:
      cmd: ansible-galaxy collection list
    register: collection_list

  - name: Printing collection
    debug:
      msg: '{{ collection_list.stdout_lines }}'

  - name: Install psycopg 
    pip:
      name: psycopg2-binary==2.9.9

  - name: Getting local python modules
    shell:
      cmd: pip list
    register: python_list

  - name: Printing collection
    debug:
      msg: '{{ python_list.stdout_lines }}'
