---
- hosts: all 
  tasks:
    - name: Retrieve host hostname
      shell: hostname
      register: hostname_var
      changed_when: False
      when: ansible_os_family == "Debian"

    - name: Print all groups
      debug:
        msg: "{{ item }}"
      loop: "{{ groups.keys() | list }}"

- hosts: localhost
  tasks:
    - name: Print all groups - local
      debug:
        msg: "{{ item }}"
      loop: "{{ groups.keys() | list }}"
      
    - name: Print local
      debug:
        msg: "Item is {{ item }}"
      loop: "{{ groups['Patch Management Lab Activated'] }}"
