---
- hosts: localhost
  become: no
  tasks:
      - name: Print template variables
        debug:
          msg: "{{ DB_HOST }}"

    # - name: Get K8S secret information
    #   kubernetes.core.k8s_info:
    #     api_version: v1
    #     kind: Secret
    #     name: awx-secret
    #     namespace: awx
    #   register: secret_info

    # - name: Decode and print variable DB_HOST
    #   debug:
    #     msg: "{{ secret_info.resources[0] }}"
