---
- hosts: localhost
  vars:
    secret: "{{ lookup('aws_secret', 'UAT/SECRET', region='us-east-2') }}"
  tasks:    
  - name: Show secret
    debug:
      msg: "{{ secret }}"

  - name: Show unique secret
    debug:
      msg: "{{ secret['DB_NAME'] }}"
